from langflow.custom import Component
from langflow.inputs import MessageTextInput, SecretStrInput
from langflow.template import Output
from langflow.schema import Message
import requests
import json

class CouchDBQueryExecutor(Component):
    display_name = "CouchDB Mango Query"
    description = "Executes JSON Mango query generated by LLM against local CouchDB"
    icon = "database" # Opsional: untuk icon di UI Langflow

    inputs = [
        MessageTextInput(
            name="mango_query", 
            display_name="Mango Query (JSON)", 
            info="JSON query from LLM (e.g., {'selector': {'koperasi': 'Sukamaju'}})",
            is_list=False
        ),
        MessageTextInput(
            name="db_url", 
            display_name="CouchDB URL", 
            value="http://localhost:5984/palmchain/_find", 
            info="Direct URL to CouchDB _find endpoint (ganti 'palmchain' dengan nama database/channel Anda)"
        ),
        MessageTextInput(
            name="username", 
            display_name="Username", 
            value="admin"
        ),
        SecretStrInput(
            name="password", 
            display_name="Password", 
            value="adminpw"
        ),
    ]

    outputs = [
        Output(display_name="Result Data", name="result_data", method="execute_query"),
    ]

    def execute_query(self) -> Message:
        headers = {"Content-Type": "application/json"}
        try:
            # Mengambil input
            query_payload = self.mango_query
            
            # Validasi jika kosong
            if not query_payload:
                return Message(text="Error: Query is empty.")
                
            # Pastikan query dalam bentuk string JSON yang valid
            if isinstance(query_payload, dict):
                query_payload = json.dumps(query_payload)
            elif isinstance(query_payload, str):
                # Terkadang LLM memberikan string block markdown ```json ... ```
                query_payload = query_payload.strip()
                if query_payload.startswith("```json"):
                    query_payload = query_payload[7:]
                if query_payload.endswith("```"):
                    query_payload = query_payload[:-3]
                query_payload = query_payload.strip()
                
            response = requests.post(
                self.db_url, 
                data=query_payload, 
                headers=headers, 
                auth=(self.username, self.password)
            )
            
            if response.status_code == 200:
                data = response.json()
                # Ekstrak array 'docs' saja agar data lebih bersih saat dibaca LLM
                docs = data.get('docs', [])
                
                # Jika hasil kosong
                if not docs:
                    return Message(text="Tidak ada data yang ditemukan di database untuk query ini.")
                    
                return Message(text=json.dumps(docs, indent=2))
            else:
                return Message(text=f"Database Error ({response.status_code}): {response.text}")
                
        except Exception as e:
            return Message(text=f"Connection Error to CouchDB: {str(e)}")
